# Generated by Django 5.2 on 2025-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=12, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('attendance', models.FloatField(default=0.0)),
            ],
        ),
    ]
